package dev.arxael.adapter.gradle

import dev.arxael.adapter.AdapterSession
import dev.arxael.adapter.BuildAdapter
import dev.arxael.adapter.RunResult
import dev.arxael.config.BoxConfig
import dev.arxael.protocol.InvokeSpec
import org.gradle.tooling.BuildException
import org.gradle.tooling.GradleConnectionException
import org.gradle.tooling.GradleConnector
import org.gradle.tooling.ProjectConnection
import java.io.ByteArrayOutputStream
import java.nio.file.Files
import java.nio.file.Path

/**
 * Gradle adapter over the Tooling API.
 *
 * Two hard-won fixes live here:
 *
 *  1. WARM CONNECTION, NEVER CLOSED PER-INVOKE. One [ProjectConnection] is opened
 *     in [open] and reused for every invocation. Closing/reopening it per build re-creates the
 *     consumer-side close-deadlock wedge. It is closed exactly once,
 *     when the worktree-server is torn down.
 *
 *  2. PER-WORKTREE WRITABLE CACHE (Gradle #8375). Concurrent worktrees on different branches
 *     sharing ONE writable build cache deadlock on LockTimeoutException. Each session therefore
 *     gets its own --project-cache-dir AND its own local build-cache directory (injected via a
 *     per-worktree init script). The Gradle user home (distribution + downloaded deps) stays
 *     shared and read-mostly — a read-only shared cache + per-worktree writable layer.
 */
class GradleAdapter : BuildAdapter {
    override val name = "gradle"

    override fun open(worktree: Path, outputBase: Path, config: BoxConfig): AdapterSession {
        Files.createDirectories(outputBase)
        val projectCache = outputBase.resolve("project-cache")
        val buildCache = outputBase.resolve("build-cache")
        Files.createDirectories(projectCache)
        Files.createDirectories(buildCache)

        // Per-worktree init script pins the LOCAL build cache to this worktree's writable layer.
        val initScript = outputBase.resolve("arxael-init.gradle")
        Files.writeString(
            initScript,
            """
            // Generated by arxael-dev-kit. Isolates the writable build cache per worktree (Gradle #8375).
            gradle.settingsEvaluated { settings ->
                settings.buildCache {
                    local {
                        directory = new File(${quote(buildCache.toString())})
                    }
                }
            }
            """.trimIndent(),
        )

        // Default: shared read-mostly user home. Experimental (ARXAEL_PER_WORKTREE_HOME=true):
        // per-worktree home removes the shared-user-home cross-process cache lock — used in limit-
        // finding to get past the lock ceiling and reach the box's true CPU/RAM wall.
        val userHome = if (config.perWorktreeHome) outputBase.resolve("gradle-user-home")
                       else config.stateDir.resolve("gradle-user-home")
        Files.createDirectories(userHome)
        // Bound the daemon leak: daemons read org.gradle.daemon.idletimeout from the user-home
        // gradle.properties — set it to daemonIdleSec (default 120s) instead of Gradle's 3h, so daemons
        // die shortly after the executor stops, while staying long enough not to thrash warm reuse.
        // (Tooling API's setDaemonMaxIdleTime was removed in Gradle 8.x; this property is the path.)
        Files.writeString(userHome.resolve("gradle.properties"),
            "org.gradle.daemon.idletimeout=${config.daemonIdleSec * 1000}\n")

        val connection: ProjectConnection = GradleConnector.newConnector()
            .useInstallation(config.gradleHome.toFile())          // offline + deterministic
            .useGradleUserHomeDir(userHome.toFile())
            .forProjectDirectory(worktree.toFile())
            .connect()

        return Session(connection, config, initScript.toString(), projectCache.toString())
    }

    private class Session(
        private val connection: ProjectConnection,
        private val config: BoxConfig,
        private val initScript: String,
        private val projectCacheDir: String,
    ) : AdapterSession {

        override fun run(spec: InvokeSpec, sink: (String) -> Unit): RunResult {
            val out = BoundedOutput(MAX_OUTPUT_BYTES)
            // Isolation + scale-to-cores args injected by the substrate. They are placed AFTER the caller's
            // (already arg-allowlisted) args in withArguments below, so on any conflicting/repeated option
            // GRADLE's last-wins rule makes the SUBSTRATE authoritative — defense-in-depth even if the allowlist
            // ever had a gap, the caller can never override our isolation (--init-script / --project-cache-dir / …).
            val injected = listOfNotNull(
                "--init-script", initScript,
                "--project-cache-dir", projectCacheDir,
                if (config.buildCache) "--build-cache" else null,
                "--parallel",
                // live: the adaptive governor raises workers as concurrency falls (slots = C*W ~ cores)
                "--max-workers=${config.liveBuildWorkers.get()}",
            )
            // Shared READ-ONLY dependency cache: per-worktree homes re-download deps (Maven 429 at scale),
            // so point builds at a shared, already-warmed RO dep cache. Gradle reads deps from it and writes
            // only NEW deps to the per-worktree writable home -> shared deps, no lock, no re-download. Env
            // (not a property) is the only knob; we replace with the full inherited env + the addition so the
            // daemon keeps PATH/JAVA_HOME etc. Constant across builds, so the warm daemon is still reused.
            val roDepCache = config.liveRoDepCache.get()
            return try {
                connection.newBuild()
                    .apply { if (spec.tasks.isNotEmpty()) forTasks(*spec.tasks.toTypedArray()) }
                    .apply { if (roDepCache != null) setEnvironmentVariables(System.getenv() + ("GRADLE_RO_DEP_CACHE" to roDepCache)) }
                    .withArguments(spec.args + injected) // injected LAST -> substrate wins (see note above)
                    .setJvmArguments("-Xmx${config.heapPerServerMb}m")
                    .setStandardOutput(out)
                    .setStandardError(out)
                    .run()
                sink(out.text())
                RunResult(success = true)
            } catch (e: BuildException) {
                // Ordinary build failure (compile error, failing test). NOT an infra fault.
                sink(out.text())
                RunResult(success = false, message = e.message?.lineSequence()?.firstOrNull())
            } catch (e: GradleConnectionException) {
                // Infrastructure fault — surface as a throw so the executor fails closed (ERROR).
                throw RuntimeException("gradle connection fault: ${e.message}", e)
            }
        }

        // Weak probe (the Tooling API has no cheap liveness ping). Real recovery is FAULT-driven instead: a
        // broken connection throws on run, and WarmExecutor.evictFaulted drops + recreates the server. (A
        // silently-HUNG build is the residual: it neither throws nor frees the permit — bounded only by the
        // caller's own patience; builds are legitimately long, so no run-timeout is imposed.)
        override fun healthy(): Boolean = true

        override fun close() {
            try { connection.close() } catch (_: Exception) { /* idempotent teardown */ }
        }
    }

    companion object {
        private const val MAX_OUTPUT_BYTES = 64 * 1024
        // Emits a Groovy double-quoted string literal for the init script. Escape backslash, quote, AND `$`
        // (Groovy GString interpolation) plus newlines — a worktree path legitimately containing `$` would
        // otherwise break the generated init script and fail every build for that worktree.
        private fun quote(s: String) = "\"" + s
            .replace("\\", "\\\\").replace("\"", "\\\"").replace("$", "\\$")
            .replace("\n", "\\n").replace("\r", "\\r") + "\""
    }
}

/** Captures build output up to a byte cap, keeping the TAIL (where failures print). The Tooling API pumps
 *  the daemon's stdout and stderr on TWO separate threads into this one sink, so write/trim/text must be
 *  synchronized — otherwise trim()'s read-modify-write (size→toByteArray→reset→write) interleaves with a
 *  concurrent write and silently drops output (possibly the exact failure tail) or exceeds the bound. */
private class BoundedOutput(private val cap: Int) : java.io.OutputStream() {
    private val buf = ByteArrayOutputStream()
    @Synchronized override fun write(b: Int) { buf.write(b); trim() }
    @Synchronized override fun write(b: ByteArray, off: Int, len: Int) { buf.write(b, off, len); trim() }
    private fun trim() {
        if (buf.size() > cap * 2) {
            val bytes = buf.toByteArray()
            buf.reset()
            buf.write(bytes, bytes.size - cap, cap)
        }
    }
    @Synchronized fun text(): String {
        val bytes = buf.toByteArray()
        val start = maxOf(0, bytes.size - cap)
        return String(bytes, start, bytes.size - start)
    }
}
